routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Somente rotas para usuarios autenticados
Route::group(['middleware' => ['auth']], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/settings/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('/settings', 'SettingController@update')->name('settings.update');
    Route::resource('personas', 'PersonaController');
});

app/Models/Persona.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Persona extends Model
{
    protected $fillable = [
        'image',
        'description'
    ];
}

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = [
        'image_background',
        'text_main',
        'game_name',
        'description_game',
        'description_form',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PersonaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Persona;
use App\Http\Requests\PersonaRequest;
use Illuminate\Support\Facades\Storage;

class PersonaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $personas = Persona::paginate(3);

        return view('persona.index',['personas' => $personas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('persona.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PersonaRequest $request)
    {

        $nameFile = null;

        if ($request->hasFile('image') && $request->file('image')->isValid()) {

            $name = uniqid(date('HisYmd'));
            $extension = $request->image->extension();
            $nameFile = "{$name}.{$extension}";
            $upload = $request->image->storeAs('images', $nameFile);

        }

        $persona = Persona::create([
            'image' => $nameFile,
            'description' => $request->description
        ]);

        return redirect()->route('personas.index')->with('status', 'Novo personagem criado!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('persona.edit', ['persona'=>Persona::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $persona = Persona::findOrFail($id);


        if ($request->hasFile('image') && $request->file('image')->isValid()) {

            $nameFile = null;
            $name = uniqid(date('HisYmd'));
            $extension = $request->image->extension();
            $nameFile = "{$name}.{$extension}";
            $upload = $request->image->storeAs('images', $nameFile);

            Storage::delete('images/'.$persona->image);

            $persona->image = $nameFile;
        }

        $persona->description = $request->description;
        $persona->save();

        return redirect()->route('personas.index')->with('status','Personagem Editado com Sucesso!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $persona = Persona::findOrFail($id);
        Storage::delete('images/'.$persona->image);
        $persona->delete();

        return redirect()->route('personas.index')->with('status','Personagem Excluido com Sucesso!');
    }
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Setting;
use Illuminate\Support\Facades\Storage;

class SettingController extends Controller
{
    private $settings = null;

    public function __construct() {
        $this->settings = Setting::first();
        if( $this->settings == null ) {
            $this->settings = Setting::create([
                'image_background' => '',
                'text_main' => '',
                'game_name' => '',
                'description_game' => '',
                'description_form' => '',
            ]);
        }
    }

    public function edit() {
        return view('settings.edit', ['settings' => $this->settings]);
    }

    public function update( Request $request ) {

        if ($request->hasFile('image_background') && $request->file('image_background')->isValid()){

                $nameFile = null;
                $name = uniqid(date('HisYmd'));
                $extension = $request->image_background->extension();
                $nameFile = "{$name}.{$extension}";
                $upload = $request->image_background->storeAs('images', $nameFile);

                if($this->settings->image_background)
                Storage::delete('images/'.$this->settings->image_background);

                $this->settings->image_background = $nameFile;

        } else {
            return redirect()->route('settings.edit')->withErrors('Erro ao salvar a imagem, verifique o tamanho ou extenção do arquivo!');
        }

        $this->settings->text_main = $request->text_main;
        $this->settings->game_name = $request->game_name;
        $this->settings->description_game = $request->description_game;
        $this->settings->description_form = $request->description_form;
        $this->settings->save();

        return redirect()->route('settings.edit')->with('status', 'Configurações atualizadas!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">Painel</div>

    <div class="card-body">
        <a href="{{route('personas.index')}}" class="btn btn-primary">Personagens</a>
        <a href="{{route('settings.edit')}}" class="btn btn-info">Configurações</a>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">

                            @yield('content')

                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
</html>

resources/views/persona/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">Criar novo personagem</div>
    <div class="card-body">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('personas.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="file" name="image" value=""/>
            <input type="text" name="description" value="" placeholder="Digite uma descrição"/>
            <input type="submit" value="Salvar"/>
        </form>
    </div>
@endsection

resources/views/persona/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">Editar personagem</div>
    <div class="card-body">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('personas.update',['id' =>$persona->id])}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <img src="{{asset('storage/images/'.$persona->image)}}" style="width: 80px"/>
            <input type="file" name="image" value="{{$persona->image}}"/>
            <input type="text" name="description" value="{{$persona->description}}" placeholder="Digite uma descrição"/>
            <input type="submit" value="Salvar"/>
        </form>
    </div>
@endsection

resources/views/persona/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">Personagens</div>
    <div class="card-body">
        @if(session('status'))
            <div class="alert alert-success">
                {{session('status')}}
            </div>
        @endif

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
<a class="btn btn-success" href="{{route('personas.create')}}">Novo Personagem</a>
<hr>
<div class="row">
<table class="table table-responsive">
    <thead>
        <tr>
            <td>#</td>
            <td>Imagem</td>
            <td>Descrição</td>
            <td>Ações</td>
        </tr>
    </thead>
    <tbody>
        @foreach( $personas as $persona )
            <tr>
                <td>{{$persona->id}}</td>
                <td><img src="{{asset('storage/images/'.$persona->image)}}" style="width: 80px"/></td>
                <td>{{$persona->description}}</td>
                <td><a href="{{route('personas.edit', ['id' => $persona->id])}}" class="btn btn-warning">Editar</a> | <form method="POST" action="{{route('personas.destroy', ['id' => $persona->id])}}">@csrf @method('DELETE')<button type="submit" class="btn btn-danger">Excluir</button></form></td>
            </tr>
        @endforeach
    </tbody>
</table>
{{$personas->links()}}
</div>
</div>
@endsection

resources/views/settings/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">Settings</div>
    <div class="card-body">

        @if(session('status'))
            <div class="alert alert-success">
                {{session('status')}}
            </div>
        @endif

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{route('settings.update')}}" class="form" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            @if($settings->image_background)
                <img src="{{asset('storage/images/'.$settings->image_background)}}" style="width: 80px"/>
            @endif
            <lable>Imagem de Fundo:</lable>
            <input type="file" name="image_background" value="{{$settings->image_background}}"/><br/><hr/>

            <lable>Texto Principal:</lable>
            <input type="text" name="text_main" value="{{$settings->text_main}}" placeholder="Digite o texto principal"/><br/><hr/>

            <lable>Nome do Jogo:</lable>
            <input type="text" name="game_name" value="{{$settings->game_name}}" placeholder="Digite o nome do jogo"/><br/><hr/>

            <lable>Descrição do Jogo:</lable>
            <input type="text" name="description_game" value="{{$settings->description_game}}" placeholder="Digite uma descrição do jogo"/><br/><hr/>

            <lable>Descrição do Formulário:</lable>
            <input type="text" name="description_form" value="{{$settings->description_form}}" placeholder="Digite uma descrição do formulário"/><br/><hr/>

            <input type="submit" value="Salvar"/>
        </form>
    </div>
@endsection